# Site
name: 'Matthew Leipzig'
description: 'This config.yml file is what we will use to edit the website.'
logo: 'assets/images/ceo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: '/mundana-theme-jekyll'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
url: "https://moxieresearch.github.io"


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Matthew Leipzig:
      name: Matthew Leipzig
      avatar: /assets/images/sam.jpg
      bio: Hi, I am Matt. I am a causal inference statistican in the Stanford CT Surgery Department. I am a proud Border Collie owner.
      email: mleipzig@stanford.edu
      twitter: https://twitter.com/MattLeipzig

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Matthew Leipzig
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]